### PR TITLE
:bug: Fix typing imports requiring Python 3.8 or newer

### LINKED ISSUE #9: Imports from typing module require Python version 3.8 or newer
There are multiple imports from the `typing` module that require Python 3.8 or newer.
https://github.com/Ackee-Blockchain/woke/blob/e96ea6aeecd2fc9dd9d7e22d822aa5783b528d79/woke/woke/e_ast_parsing/b_solc/a_ast_basic_types/__init__.py#L1

https://github.com/Ackee-Blockchain/woke/blob/e96ea6aeecd2fc9dd9d7e22d822aa5783b528d79/woke/woke/e_ast_parsing/b_solc/c_ast_nodes/__init__.py#L1

### PR DESCRIPTION
**Pull request by michprev**
Fixes #9.

### CODE REVIEW

File: woke/setup.py [hunk 1]
```diff
@@ -2,6 +2,7 @@
 
 install_requires = [
     "pydantic >= 1.9.0",
+    "typing_extensions >= 4.0, < 5",
```
Comment (hacker-DOM) [inline woke/setup.py:5]: Should we put this in `extras_require['dev']` or `['tests']`?

Comment (hacker-DOM) [reply woke/setup.py:5]: I think `['tests']` might be better?

**Review by hacker-DOM — CHANGES_REQUESTED** [review]

File: woke/setup.py (hunk 1 above)
Comment (michprev) [reply woke/setup.py:5]: Should be in `install_requires`, I believe. Types `Literal` and `Annotated` are not part of Python 3.7 `typing` module so any import from `woke/woke/e_ast_parsing/b_solc/c_ast_nodes/__init__.py` causes an import error:
`ImportError: cannot import name 'Annotated' from 'typing' (/usr/lib/python3.7/typing.py)`

Comment (hacker-DOM) [reply woke/setup.py:5]: I see. Correct me if I'm wrong: The behavior we want is:

- the program is executable on 3.7 (so we don't have to bump the Python version until it's really necessary)
- type checking also works on 3.7
- ideally we don't want type checking libs to be part of the executable

Does it accomplish these goals if we use conditionals? Something like

```python
from typing import TYPE_CHECKING
if TYPE_CHECKING:
  from typing_extensions import ...
```

Comment (hacker-DOM) [reply woke/setup.py:5]: Is it safe to assume that 'type checking' only needs to be run in `test/dev` mode? I think so.. Interested to hear your opinion :-)

Comment (michprev) [reply woke/setup.py:5]: > I see. Correct me if I'm wrong: The behavior we want is:
> 
> * the program is executable on 3.7 (so we don't have to bump the Python version until it's really necessary)

Yes

> * type checking also works on 3.7

Yes

> * ideally we don't want type checking libs to be part of the executable
> 
> Does it accomplish these goals if we use conditionals? Something like
> 
> ```python
> from typing import TYPE_CHECKING
> if TYPE_CHECKING:
>   from typing_extensions import ...
> ```

We have to distinguish between static type checking (MyPy and the other tools) and type checking at runtime (this is done by `pydantic`).
Static type checking should only be enforced in `test/dev`, sure.

But we also use `pydantic` to perform AST JSON validation at runtime. In my opinion, this also should be done in the executable (i.e. non-development environment). It is much better to tell the user "Oops we failed to parse this Solidity file" instead of silently ignoring the bug (= incompatible AST JSON).

We need types `Literal` and `Annotated` to perform `pydantic` validation.

Comment (hacker-DOM) [reply woke/setup.py:5]: Ahhh ok
